name: Code Quality checks

on:
  pull_request:
    branches: [main]

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Check prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .
          only_changed: True
